package com.godnedy.address;

enum AddressType {
    SIMPLE,
    COMPLEX_STREET,
    HOUSE_COMMA_STREET,
    STREET_COMMA_HOUSE,
    HOUSE_STREET,
    STREET_HOUSE_NUMBER_SUFFIX,
    STREET_COMMA_HOUSE_NUMBER_SUFFIX,
    STREET_NUMBER_HOUSE_NUMBER_SUFFIX,
    UNKNOWN
}
